plugins {
    id "org.mifos.conventions.gradle.boot.core"
    id "org.openapi.generator"
    id "com.google.protobuf"
}

dependencies {
    api "jakarta.validation:jakarta.validation-api"

    annotationProcessor "org.mapstruct:mapstruct-processor"
    compileOnly "org.mapstruct:mapstruct-processor"
}
