plugins {
    id "org.mifos.conventions.gradle.base.java"
    id "org.mifos.conventions.gradle.base.java.test.spring"
}

dependencies {
    annotationProcessor "org.projectlombok:lombok"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    annotationProcessor "org.springframework.boot:spring-boot-autoconfigure-processor"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
