plugins {
    id "org.mifos.conventions.gradle.boot.core.persistence.implementation"
}

dependencies {
    // implementation "io.github.openfeign.querydsl:querydsl-sql-spring"

    implementation "org.postgresql:postgresql"
    implementation "net.postgis:postgis-jdbc"
    implementation "net.postgis:postgis-jdbc-jts"
    implementation "net.postgis:postgis-jdbc-java2d"

    // TODO: this is just to make the applications work for now; remove later
    implementation "com.h2database:h2"

    testImplementation "org.mifos.commons.boot:mifos-commons-boot-testing:0.1.0-SNAPSHOT"
}
