plugins {
    id "org.mifos.conventions.gradle.boot.core.persistence.implementation"
}

dependencies {
    implementation "org.mifos.commons.boot:mifos-commons-boot-persistence-jpa-imperative:0.1.0-SNAPSHOT:0.1.0-SNAPSHOT"

    // TODO: finish this!

    testImplementation "org.mifos.commons.boot:mifos-commons-boot-testing:0.1.0-SNAPSHOT"
}
