plugins {
    id "org.mifos.conventions.gradle.boot.core.cli.implementation"
}

dependencies {
    api "org.mifos.commons.boot:mifos-commons-boot-cli-tamboui:0.1.0-SNAPSHOT"
    api "dev.tamboui:tamboui-toolkit"
    api "dev.tamboui:tamboui-css"
    api "dev.tamboui:tamboui-aesh-backend"
    api "dev.tamboui:tamboui-image"
}
